//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PieShopApp.API.Endpoint.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PieShopApp.API.Endpoint.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting application log..
        /// </summary>
        public static string ApplicationLog_Delete {
            get {
                return ResourceManager.GetString("ApplicationLog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving application log by id..
        /// </summary>
        public static string ApplicationLog_Id {
            get {
                return ResourceManager.GetString("ApplicationLog_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving application logs..
        /// </summary>
        public static string ApplicationLog_List {
            get {
                return ResourceManager.GetString("ApplicationLog_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting audit log..
        /// </summary>
        public static string AuditLog_Delete {
            get {
                return ResourceManager.GetString("AuditLog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving audit log by id..
        /// </summary>
        public static string AuditLog_Id {
            get {
                return ResourceManager.GetString("AuditLog_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting new audit log..
        /// </summary>
        public static string AuditLog_Insert {
            get {
                return ResourceManager.GetString("AuditLog_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving audit logs..
        /// </summary>
        public static string AuditLog_List {
            get {
                return ResourceManager.GetString("AuditLog_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting current user information..
        /// </summary>
        public static string Auth_GetCurrentUser {
            get {
                return ResourceManager.GetString("Auth_GetCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting token..
        /// </summary>
        public static string Auth_GetToken {
            get {
                return ResourceManager.GetString("Auth_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging user..
        /// </summary>
        public static string Auth_Login {
            get {
                return ResourceManager.GetString("Auth_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting refresh token..
        /// </summary>
        public static string Auth_RefreshToken {
            get {
                return ResourceManager.GetString("Auth_RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving categories with pies..
        /// </summary>
        public static string Category_CategoriesWithPies {
            get {
                return ResourceManager.GetString("Category_CategoriesWithPies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting category..
        /// </summary>
        public static string Category_Delete {
            get {
                return ResourceManager.GetString("Category_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving category by id..
        /// </summary>
        public static string Category_Id {
            get {
                return ResourceManager.GetString("Category_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting new category..
        /// </summary>
        public static string Category_Insert {
            get {
                return ResourceManager.GetString("Category_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving categories..
        /// </summary>
        public static string Category_List {
            get {
                return ResourceManager.GetString("Category_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating category..
        /// </summary>
        public static string Category_Update {
            get {
                return ResourceManager.GetString("Category_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email could not be sent..
        /// </summary>
        public static string Email_Send {
            get {
                return ResourceManager.GetString("Email_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving email templates..
        /// </summary>
        public static string EmailTemplate_List {
            get {
                return ResourceManager.GetString("EmailTemplate_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating email template..
        /// </summary>
        public static string EmailTemplate_Update {
            get {
                return ResourceManager.GetString("EmailTemplate_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error changing password..
        /// </summary>
        public static string MobileAuth_ChangePassword {
            get {
                return ResourceManager.GetString("MobileAuth_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in forgot password..
        /// </summary>
        public static string MobileAuth_ForgotPassword {
            get {
                return ResourceManager.GetString("MobileAuth_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting current user information..
        /// </summary>
        public static string MobileAuth_GetCurrentUser {
            get {
                return ResourceManager.GetString("MobileAuth_GetCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting token..
        /// </summary>
        public static string MobileAuth_GetToken {
            get {
                return ResourceManager.GetString("MobileAuth_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging user..
        /// </summary>
        public static string MobileAuth_Login {
            get {
                return ResourceManager.GetString("MobileAuth_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error registering user..
        /// </summary>
        public static string MobileAuth_Register {
            get {
                return ResourceManager.GetString("MobileAuth_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving pie by category id..
        /// </summary>
        public static string Pie_CategoryId {
            get {
                return ResourceManager.GetString("Pie_CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting pie..
        /// </summary>
        public static string Pie_Delete {
            get {
                return ResourceManager.GetString("Pie_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving pie by id..
        /// </summary>
        public static string Pie_Id {
            get {
                return ResourceManager.GetString("Pie_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting new pie..
        /// </summary>
        public static string Pie_Insert {
            get {
                return ResourceManager.GetString("Pie_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving pies..
        /// </summary>
        public static string Pie_List {
            get {
                return ResourceManager.GetString("Pie_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating pie..
        /// </summary>
        public static string Pie_Update {
            get {
                return ResourceManager.GetString("Pie_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS could not be sent..
        /// </summary>
        public static string SMS_Send {
            get {
                return ResourceManager.GetString("SMS_Send", resourceCulture);
            }
        }
    }
}
